language: php

php:
  - "5.5"
  - "5.4"

before_script:
  - psql -c 'create database pitchblade_test;' -U postgres
  - composer install

script: phpunit --configuration phpunit.xml.dist --coverage-text
